<?php

namespace Database\Seeders;

use App\Models\Accommodation;
use App\Models\User;
use Illuminate\Database\Seeder;

class AccommodationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create owner users
        $owners = User::whereIn('role', ['owner', 'admin'])->get();
        
        if ($owners->isEmpty()) {
            // Create sample owners if none exist
            $owner1 = User::create([
                'name' => 'Maria Santos',
                'email' => 'maria@impasugong.com',
                'password' => bcrypt('password123'),
                'role' => 'owner',
                'phone' => '+63 912 345 6789',
                'address' => 'Brgy. Poblacion, Impasugong',
                'bio' => 'Local hotelier with 10 years experience in hospitality.',
            ]);
            
            $owner2 = User::create([
                'name' => 'Juan dela Cruz',
                'email' => 'juan@impasugong.com',
                'password' => bcrypt('password123'),
                'role' => 'owner',
                'phone' => '+63 917 890 1234',
                'address' => 'Brgy. Centro, Impasugong',
                'bio' => 'Property owner specializing in vacation rentals.',
            ]);
            
            $owners = collect([$owner1, $owner2]);
        }

        $accommodations = [
            // Traveller-Inns
            [
                'name' => 'Impasugong Mountain View Inn',
                'type' => 'traveller-inn',
                'description' => 'A cozy mountain-view inn located in the heart of Impasugong. Perfect for travelers seeking affordable comfort with scenic views. Features clean rooms, hot showers, and friendly staff ready to assist you.',
                'address' => 'Poblacion East, Impasugong, Bukidnon',
                'barangay' => 'Poblacion',
                'price_per_night' => 1500,
                'price_per_day' => 1200,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'max_guests' => 4,
                'amenities' => ['WiFi', 'Hot Shower', 'Parking', 'Restaurant', 'Room Service', 'Air Conditioning'],
                'house_rules' => 'No smoking inside rooms. Pets allowed with prior notice. Check-in: 2PM, Check-out: 11AM.',
                'check_in_instructions' => 'Proceed to the front desk upon arrival. Present your booking confirmation.',
                'rating' => 4.5,
                'total_reviews' => 128,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => true,
                'latitude' => 8.4567,
                'longitude' => 124.9876,
                'images' => ['inn1.jpg', 'inn2.jpg', 'inn3.jpg'],
                'owner_id' => $owners[0]->id ?? 1,
            ],
            [
                'name' => 'Highland Travellers Inn',
                'type' => 'traveller-inn',
                'description' => 'Budget-friendly accommodation with panoramic mountain views. Ideal for backpackers and business travelers. Walking distance to town center and public transport.',
                'address' => 'Poblacion West, Impasugong, Bukidnon',
                'barangay' => 'Poblacion',
                'price_per_night' => 800,
                'price_per_day' => 650,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'max_guests' => 2,
                'amenities' => ['WiFi', 'Hot Shower', 'Parking', 'Fan', 'Cable TV'],
                'house_rules' => 'Quiet hours from 10PM to 6AM. No outside food allowed.',
                'check_in_instructions' => 'Ring the bell at the front desk. Night guard available until 11PM.',
                'rating' => 4.2,
                'total_reviews' => 89,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => false,
                'latitude' => 8.4589,
                'longitude' => 124.9854,
                'images' => ['inn4.jpg', 'inn5.jpg'],
                'owner_id' => $owners[1]->id ?? 2,
            ],
            [
                'name' => 'Town Center Inn',
                'type' => 'traveller-inn',
                'description' => 'Conveniently located at the town center of Impasugong. Perfect for those who want to explore the municipality. Clean, safe, and affordable accommodation.',
                'address' => 'Centro, Impasugong, Bukidnon',
                'barangay' => 'Poblacion',
                'price_per_night' => 1200,
                'price_per_day' => 1000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'max_guests' => 2,
                'amenities' => ['WiFi', 'Hot Shower', 'Air Conditioning', 'Cable TV', '24/7 Security'],
                'house_rules' => 'Visitors must register at front desk. No illegal activities.',
                'check_in_instructions' => 'Main entrance facing the town plaza. Parking available behind the building.',
                'rating' => 4.0,
                'total_reviews' => 156,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => true,
                'latitude' => 8.4555,
                'longitude' => 124.9890,
                'images' => ['inn1.jpg', 'inn2.jpg', 'inn3.jpg', 'inn4.jpg'],
                'owner_id' => $owners[0]->id ?? 1,
            ],
            
            // Airbnb-style
            [
                'name' => 'Cozy Garden House',
                'type' => 'airbnb',
                'description' => 'A beautiful private house with a lush garden. Perfect for families or groups. Features a fully equipped kitchen, outdoor seating area, and serene environment.',
                'address' => 'Kapitan, Impasugong, Bukidnon',
                'barangay' => 'Kapitan',
                'price_per_night' => 2800,
                'price_per_day' => 2500,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'max_guests' => 6,
                'amenities' => ['WiFi', 'Kitchen', 'Hot Shower', 'Parking', 'Garden', 'Air Conditioning', 'Washer', 'TV'],
                'house_rules' => 'Respect neighbors. No loud parties after 10PM. Smoking allowed in designated areas only.',
                'check_in_instructions' => 'Self check-in with keybox. Code will be sent to your email.',
                'rating' => 4.9,
                'total_reviews' => 45,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => true,
                'latitude' => 8.4623,
                'longitude' => 124.9789,
                'images' => ['airbnb1.jpg', 'airbnb2.jpg', 'airbnb3.jpg'],
                'owner_id' => $owners[1]->id ?? 2,
            ],
            [
                'name' => 'Forest Cabin Retreat',
                'type' => 'airbnb',
                'description' => 'Escape to nature in this rustic forest cabin. Experience the tranquility of Impasugong\'s mountains. Perfect for couples seeking a romantic getaway.',
                'address' => 'Malitbog, Impasugong, Bukidnon',
                'barangay' => 'Malitbog',
                'price_per_night' => 3500,
                'price_per_day' => 3000,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'max_guests' => 4,
                'amenities' => ['WiFi', 'Fireplace', 'Hot Shower', 'Kitchen', 'Mountain View', 'Hiking Trails', 'BBQ Grill'],
                'house_rules' => 'Campfire only in designated fire pit. Leave no trace policy.',
                'check_in_instructions' => 'Meet at the main road junction. Guide will escort you to the cabin.',
                'rating' => 4.8,
                'total_reviews' => 32,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => true,
                'latitude' => 8.4789,
                'longitude' => 124.9567,
                'images' => ['airbnb1.jpg', 'airbnb2.jpg', 'airbnb3.jpg', 'airbnb4.jpg'],
                'owner_id' => $owners[0]->id ?? 1,
            ],
            [
                'name' => 'Lakeside Villa',
                'type' => 'airbnb',
                'description' => 'Stunning lakeside villa with breathtaking views. Features floor-to-ceiling windows, private dock, and direct lake access for swimming and fishing.',
                'address' => 'Bontoc, Impasugong, Bukidnon',
                'barangay' => 'Bontoc',
                'price_per_night' => 5500,
                'price_per_day' => 5000,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'max_guests' => 8,
                'amenities' => ['WiFi', 'Kitchen', 'Hot Shower', 'Lake Access', 'Private Dock', 'Air Conditioning', 'TV', 'Parking', 'Swimming', 'Fishing Equipment'],
                'house_rules' => 'Children must be supervised near water. No jet skis or motorized watercraft.',
                'check_in_instructions' => 'Gate code will be sent upon confirmation. Private parking available.',
                'rating' => 4.95,
                'total_reviews' => 18,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => true,
                'latitude' => 8.4656,
                'longitude' => 124.9689,
                'images' => ['airbnb2.jpg', 'airbnb3.jpg', 'airbnb4.jpg'],
                'owner_id' => $owners[1]->id ?? 2,
            ],
            [
                'name' => 'Bamboo Eco House',
                'type' => 'airbnb',
                'description' => 'Sustainable bamboo eco-house in the mountains. Off-grid living with solar power and rainwater collection. Perfect for eco-conscious travelers.',
                'address' => 'Kalingag, Impasugong, Bukidnon',
                'barangay' => 'Kalingag',
                'price_per_night' => 2200,
                'price_per_day' => 1800,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'max_guests' => 4,
                'amenities' => ['WiFi', 'Solar Power', 'Rainwater Shower', 'Kitchen', 'Hammocks', 'Nature Trails'],
                'house_rules' => 'Conserve water and electricity. Compost toilet usage required.',
                'check_in_instructions' => '2km hike from main road. Guided tour included on arrival.',
                'rating' => 4.7,
                'total_reviews' => 28,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => false,
                'latitude' => 8.4890,
                'longitude' => 124.9456,
                'images' => ['airbnb1.jpg', 'airbnb4.jpg'],
                'owner_id' => $owners[0]->id ?? 1,
            ],
            
            // Daily Rentals
            [
                'name' => 'Riverside Apartment',
                'type' => 'daily-rental',
                'description' => 'Modern apartment by the river. Perfect for short stays. Walking distance to restaurants and shops. Ideal for business travelers.',
                'address' => 'Centro, Impasugong, Bukidnon',
                'barangay' => 'Poblacion',
                'price_per_night' => 1200,
                'price_per_day' => 1000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'max_guests' => 2,
                'amenities' => ['WiFi', 'Air Conditioning', 'Hot Shower', 'Cable TV', 'Kitchenette', 'Parking'],
                'house_rules' => 'No pets. No smoking. Quiet environment.',
                'check_in_instructions' => 'Apartment building next to Town Hall. Unit 3B on third floor.',
                'rating' => 4.3,
                'total_reviews' => 67,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => false,
                'latitude' => 8.4545,
                'longitude' => 124.9878,
                'images' => ['2.jpg', '1.jpg'],
                'owner_id' => $owners[1]->id ?? 2,
            ],
            [
                'name' => 'Villa Rosa',
                'type' => 'daily-rental',
                'description' => 'Elegant villa perfect for family gatherings or group events. Features a large garden, pool area, and outdoor kitchen. Daily or weekly rates available.',
                'address' => 'Haguit, Impasugong, Bukidnon',
                'barangay' => 'Haguit',
                'price_per_night' => 4000,
                'price_per_day' => 3500,
                'bedrooms' => 5,
                'bathrooms' => 3,
                'max_guests' => 10,
                'amenities' => ['WiFi', 'Swimming Pool', 'Air Conditioning', 'Hot Shower', 'Kitchen', 'Parking', 'Garden', 'BBQ Area', 'TV'],
                'house_rules' => 'Events must end by 10PM. Pool usage from 6AM to 8PM only.',
                'check_in_instructions' => 'Villa entrance from the main road. Caretaker available on-site.',
                'rating' => 4.6,
                'total_reviews' => 42,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => true,
                'latitude' => 8.4689,
                'longitude' => 124.9723,
                'images' => ['accommodation1.jpg', 'COMMUNAL.jpg'],
                'owner_id' => $owners[0]->id ?? 1,
            ],
            [
                'name' => 'Mountain Lodge Resort',
                'type' => 'daily-rental',
                'description' => 'Full-service mountain resort with comfortable rooms and cabin-style accommodations. Features restaurant, conference hall, and adventure activities.',
                'address' => 'Kalingag, Impasugong, Bukidnon',
                'barangay' => 'Kalingag',
                'price_per_night' => 2000,
                'price_per_day' => 1800,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'max_guests' => 6,
                'amenities' => ['WiFi', 'Restaurant', 'Hot Shower', 'Air Conditioning', 'Parking', 'Conference Hall', 'Zip Line', 'Team Building Area'],
                'house_rules' => 'Respect other guests. Adventure activities require signed waiver.',
                'check_in_instructions' => 'Reception open 24/7. Guided mountain treks available upon request.',
                'rating' => 4.4,
                'total_reviews' => 95,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => true,
                'latitude' => 8.4856,
                'longitude' => 124.9512,
                'images' => ['inn2.jpg', 'inn3.jpg', 'inn4.jpg', 'inn5.jpg'],
                'owner_id' => $owners[1]->id ?? 2,
            ],
            [
                'name' => 'Coffee Farm Cottage',
                'type' => 'daily-rental',
                'description' => 'Stay in a traditional bukidnon cottage on a working coffee farm. Experience local culture with farm-to-table meals and coffee tasting tours.',
                'address' => 'Mabuhay, Impasugong, Bukidnon',
                'barangay' => 'Mabuhay',
                'price_per_night' => 1800,
                'price_per_day' => 1500,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'max_guests' => 4,
                'amenities' => ['WiFi', 'Hot Shower', 'Farm Meals', 'Coffee Tour', 'Hiking', 'Parking', 'Fan'],
                'house_rules' => 'Respect farm workers and equipment. Guided tours only.',
                'check_in_instructions' => 'Farm entrance 5km from town center. Advance booking required for farm activities.',
                'rating' => 4.7,
                'total_reviews' => 38,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => false,
                'latitude' => 8.4723,
                'longitude' => 124.9598,
                'images' => ['airbnb3.jpg', 'airbnb4.jpg'],
                'owner_id' => $owners[0]->id ?? 1,
            ],
            [
                'name' => 'Traditional Bahay Kubo',
                'type' => 'daily-rental',
                'description' => 'Authentic bahay kubo (nipa hut) experience. Stay in a traditional Filipino house with modern amenities. Perfect for cultural immersion.',
                'address' => 'Poblacion, Impasugong, Bukidnon',
                'barangay' => 'Poblacion',
                'price_per_night' => 1500,
                'price_per_day' => 1200,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'max_guests' => 3,
                'amenities' => ['WiFi', 'Hot Shower', 'Air Conditioning', 'Fan', 'Traditional Design', 'Parking'],
                'house_rules' => 'Remove shoes before entering. Respect traditional customs.',
                'check_in_instructions' => 'Located in cultural village complex. Check-in at visitor center.',
                'rating' => 4.5,
                'total_reviews' => 52,
                'is_available' => true,
                'is_verified' => true,
                'is_featured' => false,
                'latitude' => 8.4578,
                'longitude' => 124.9865,
                'images' => ['COMMUNAL.jpg', '1.jpg', '2.jpg'],
                'owner_id' => $owners[1]->id ?? 2,
            ],
        ];

        foreach ($accommodations as $index => $data) {
            $accommodation = Accommodation::create([
                'owner_id' => $data['owner_id'],
                'name' => $data['name'],
                'type' => $data['type'],
                'description' => $data['description'],
                'address' => $data['address'],
                'barangay' => $data['barangay'],
                'price_per_night' => $data['price_per_night'],
                'price_per_day' => $data['price_per_day'],
                'bedrooms' => $data['bedrooms'],
                'bathrooms' => $data['bathrooms'],
                'max_guests' => $data['max_guests'],
                'amenities' => $data['amenities'],
                'house_rules' => $data['house_rules'],
                'check_in_instructions' => $data['check_in_instructions'],
                'rating' => $data['rating'],
                'total_reviews' => $data['total_reviews'],
                'is_available' => $data['is_available'],
                'is_verified' => $data['is_verified'],
                'is_featured' => $data['is_featured'],
                'latitude' => $data['latitude'],
                'longitude' => $data['longitude'],
                'images' => $data['images'],
            ]);
            
            echo "Created: {$accommodation->name}\n";
        }
        
        $this->command->info('Accommodation seeder completed successfully!');
        $this->command->info('Total accommodations created: ' . count($accommodations));
    }
}

